# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en

zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 紫龙的个人网站
  params:
    description: 紫龙的个人网站
  menu:
    main:
      - name: 主页
        url: /
        weight: 10
      - name: 消息
        url: /#events
        weight: 20
      - name: 文章
        url: /#papers
        weight: 30
      - name: 项目
        url: projects/
        weight: 40
      - name: 经历
        url: experience/
        weight: 50
